# Single node Mapillary training recipe
# Requires 32GB GPU

CMD: "CUDA_VISIBLE_DEVICES=4,5,6,7 python -m torch.distributed.launch --nproc_per_node=4 train.py"

HPARAMS: [
  {
   dataset: mapillary,
   map_version: "v1.2",
   cv: 0,
   result_dir: LOGDIR,

   pre_size: 2177,
   crop_size: "720,1280", # H,W
   map_eval_size: 1280,
   syncbn: true,
   apex: true,
   fp16: true,
   gblur: true,

   bs_trn: 2,

   lr_schedule: poly,
   poly_exp: 1.0,
   optimizer: sgd,
   lr: 5e-3,
   max_epoch: 200,
   rmi_loss: true,

   arch: ocrnet.HRNet_Mscale,
   n_scales: '0.5,1.0,2.0',
  #  resume: "logs/train_mapillary/prophetic-cockle_2021.06.30_11.06/last_checkpoint_ep55.pth",
  }
]
